import insta from "../src/Assets/images/insta.png"
import message from "../src/Assets/images/message.png"
import skype from "../src/Assets/images/skype.png"
import google from "../src/Assets/images/google.png"
import slack from "../src/Assets/images/slack.png"
import tiktok from "../src/Assets/images/tiktok.png"
import dribble from "../src/Assets/images/dribble.png"
import whats from "../src/Assets/images/whats.png"
import chat from "../src/Assets/images/chat.png"
import secone from "../src/Assets/images/secone.png"
import sectwo from "../src/Assets/images/sectwo.png"
import secthree from "../src/Assets/images/secthree.png"
import testone from "../src/Assets/images/testone.png"
import rating from "../src/Assets/images/rating.png"
import testtwo from "../src/Assets/images/testtwo.png"
import testthree from "../src/Assets/images/testthree.png"
import testfour from "../src/Assets/images/testfour.png"
import footone from "../src/Assets/images/footone.png"
import foottwo from "../src/Assets/images/foottwo.png"
import footthree from "../src/Assets/images/footthree.png"
import footfour from "../src/Assets/images/footfour.png"
import border from "../src/Assets/images/border.png"
import borderright from "../src/Assets/images/borderright.png"
import teamone from "../src/Assets/images/teamone.png"
import teamtwo from "../src/Assets/images/teamtwo.png"
import teamthree from "../src/Assets/images/teamthree.png"
import aboutmedone from "../src/Assets/images/aboutmedone.png"
import aboutmedtwo from "../src/Assets/images/aboutmedtwo.png"
import aboutmedthree from "../src/Assets/images/aboutmedthree.png"
import portimg from "../src/Assets/images/portimg.png"
import holdingone from "../src/Assets/images/holdingone.png"
import holdingtwo from "../src/Assets/images/holdingtwo.png"
import holdingthree from "../src/Assets/images/holdingthree.png"
import holdingfour from "../src/Assets/images/holdingfour.png"
import holdingfive from "../src/Assets/images/holdingfive.png"
import holdingsix from "../src/Assets/images/holdingsix.png"
import chrome from "../src/Assets/images/chrome.png"
import gamehomebg from "../src/Assets/images/gamehomebg.png"
import gameone from "../src/Assets/images/gameone.png"
import gametwo from "../src/Assets/images/gametwo.png"
import gamethree from "../src/Assets/images/gamethree.png"
import gamefour from "../src/Assets/images/gamefour.png"
import registergoogle from "../src/Assets/images/registergoogle.png"
import registerfacebook from "../src/Assets/images/registerfacebook.png"
import coinmeta from "../src/Assets/images/coinmeta.png"
import coinprofile from "../src/Assets/images/coinprofile.png"
import metamask from "../src/Assets/images/metamask.png"
import playerone from "../src/Assets/images/playerone.png"
import playertwo from "../src/Assets/images/playertwo.png"
import playerthree from "../src/Assets/images/playerthree.png"
import playerfour from "../src/Assets/images/playerfour.png"
import playerfive from "../src/Assets/images/playerfive.png"
import contvector from "../src/Assets/images/contvector.png"
import aboutjourney from "../src/Assets/images/aboutjourney.png"
import aboutculture from "../src/Assets/images/aboutculture.png"
import awardone from "../src/Assets/images/awardone.png"
import awardtwo from "../src/Assets/images/awardtwo.png"
import awardthree from "../src/Assets/images/awardthree.png"
import awardfour from "../src/Assets/images/awardfour.png"
import clubone from "../src/Assets/images/clubone.png"
import clubtwo from "../src/Assets/images/clubtwo.png"
import clubassets from "../src/Assets/images/clubassets.png"
import playbtone from "../src/Assets/images/playbtone.png"
import playbttwo from "../src/Assets/images/playbttwo.png"
import playbtthree from "../src/Assets/images/playbtthree.png"
import playbtfour from "../src/Assets/images/playbtfour.png"
import plan from "../src/Assets/images/plan.png"

export const images={
   insta,skype,message,google,slack,tiktok,dribble,whats,chat,secone,sectwo,secthree,testone,rating,
   testtwo,testthree,testfour,footone,foottwo,footthree,footfour,border,borderright,teamone,teamtwo,teamthree,aboutmedone,aboutmedtwo,aboutmedthree,
   portimg,holdingone,holdingtwo,holdingthree,holdingfour,holdingfive,holdingsix,chrome,gamehomebg,gameone,gametwo,gamethree,gamefour,
   registerfacebook,registergoogle,coinmeta,coinprofile,metamask,playerone,playertwo,playerthree,playerfour,playerfive,contvector,
   aboutjourney,aboutculture,awardone,awardtwo,awardthree,awardfour,clubone,clubtwo,clubassets,playbtone,playbttwo,playbtthree,playbtfour,plan,
}